### ISSUE TITLE
Discussion: should nxus-dataset offer a query API that abstracts details of the data storage, or should applications do their own data access directly?

### ISSUE THREAD

**Issue by ScottMaxson** [seabourne/nxus-dataset#2]
The current API, implemented [here](https://github.com/seabourne/nxus-dataset/blob/afd6bf2488d4c5277c0935ed2f7bae643c450820/src/models/DataPresentation.js#L36-L70) , doesn't do the back-end queries themselves, but rather takes a batch of DataSet(s) and child DataRow(s) and filters a (possibly ~ transformed) view containing data for a single DataPresentation.

Is this the right API for most applications? It seems that the downside here is that each application is going to have to understand, at least at some level, the implementation details of nxus-dataset's data model, so there isn't much O-O hiding of those details.

The argument for having applications do their own storage access is (possibly) overall performance and efficiency, so round trips to the db can be better optimized.

**Comment by loppear** [comment]
Is there a case where an application would otherwise be reading/querying dataset/rows for a route to do other things with it and be expected to know something of their implementation? Or is the "round trips to the db" aspect just that an application "knows" it's going to have 5 DataPresentations using some of the same fields?

At first glance I do think there should be a query API for getting DataSet/Rows that encapsulates `storage.get('dataset').find().populate('datarow')..` or whatever BUT I'd be fine with that being separate from the DataPresentation call, that DataPresentation is passed the results of that "get all the data for this route" call rather than doing the query itself. Unless you think the typical use case will be JUST interacting with DataPresentation.

What would the arguments to a replacement to `DataPresentation.extractFieldData` be if it were to do the query itself? a filter on a primary column and a list of fields?

**Comment by ScottMaxson** [comment]
Speaking to @loppear 's points/questions:
1. It seems like applications might want to use "raw" dataset/datarow queries elsewhere, since the data relationship is super simple as relational parent-child and, I think, unlikely to change. Whether those queries would be a super-set of what's needed for any DataPresentation's also on that page/route - I don't know.... In GWLI they were, sometimes. It seems likely that a page could be a mix of visualizations tied to a DataPresentation, and other objects coming from the back-end. So ... (to my next point/question)
2. With WL, is it "more efficient" to do things like `.spread( model1.query(...), model2.query(...) ).then(...)` rather than chaining a series of individual query-then-query-then-query statements? Is there connection sharing or re-use in WL that favors this parallel query form? Or is is the real 'efficiency' in not asking for the same stuff more than once?
3. Since a DataPresentation instance contains what's needed to query just the DataSet+DataRow records relevant to it, what if there was a no-argument `load()` method that goes to the back end and returns the related data? Advantage here is that it hides the details of how DataPresentation associations are handled in the design -- which, BTW, currently is held partly in an un-modeled JSON attribute stored without db-aware associations. Since that detail might change, I'd prefer not exposing it in the API.

**Comment by loppear** [comment]
The efficiency of those two approaches doesn't really have to do with WL (yes there is connection sharing, iirc) but with the Promise API - `Promise.all([query1, query2).spread(result1, result2)` executes them in parallel while `query1.then( return query2).then()` implies the second query will wait / needs something from the first. More concerned (but possibly not too much) about multiple queries for the same data. Given that a DataPresentation already knows what fields it needs, that helps with being able to use Promise.all() with your suggested `dataPresentationInstance.load()`, seems reasonable to me. As we get more examples, we can decide if there's an alternate static method for `loadMany` or something that could avoid duplicate queries if the many share fields etc.

**Comment by ScottMaxson** [comment]
This has been implemented with methods in the `DataSets` class `loadPresentations(query, keys)` and the convenience class `loadPresentationsByName`.
